In [2]:
!pip install numpy

In [2]:
import numpy as np
import pandas as pd

# Uploading file

In [4]:
df = pd.read_csv("C:/Users/HAVE A NICE DAY/OneDrive/Documents/Indian_Cricket_Team_Dataset.csv")
df

Player Name  Age  Matches Played  Batting Average  Strike Rate
0       Player_1   26             456            27.70       188.21
1       Player_2   23             154            24.61       139.34
2       Player_3   32             210            36.87       182.79
3       Player_4   34             426            51.81       178.77
4       Player_5   30             221            49.80       162.44
..           ...  ...             ...              ...          ...
995   Player_996   24             279            23.46       187.80
996   Player_997   28             344            29.47       160.55
997   Player_998   23             126            49.30       124.71
998   Player_999   35              16            41.93       135.59
999  Player_1000   30             146            25.12       108.39

[1000 rows x 5 columns]

# 1. Convert 'Age' column to a NumPy array. 

In [8]:
numpy = df['Age'].to_numpy()
numpy


array([26, 23, 32, 34, 30, 27, 32, 24, 26, 29, 22, 26, 30, 30, 27, 24, 23,
       27, 27, 22, 25, 24, 21, 27, 31, 33, 25, 21, 35, 31, 24, 20, 31, 29,
       25, 32, 31, 28, 20, 30, 30, 34, 29, 35, 31, 31, 35, 34, 33, 33, 34,
       33, 22, 31, 26, 23, 35, 28, 22, 24, 22, 26, 24, 28, 26, 21, 23, 28,
       31, 33, 21, 29, 28, 29, 24, 21, 23, 31, 34, 31, 26, 31, 32, 27, 34,
       22, 33, 20, 23, 21, 27, 23, 21, 33, 25, 25, 29, 23, 25, 32, 34, 21,
       29, 31, 21, 29, 33, 23, 33, 34, 35, 34, 27, 33, 26, 31, 28, 33, 27,
       24, 35, 32, 21, 34, 24, 27, 29, 28, 31, 31, 31, 32, 28, 32, 34, 32,
       20, 28, 26, 28, 27, 20, 31, 27, 27, 34, 30, 22, 20, 27, 22, 22, 20,
       30, 24, 29, 26, 29, 28, 31, 26, 28, 27, 31, 21, 20, 35, 26, 26, 33,
       27, 24, 22, 31, 27, 25, 30, 22, 20, 22, 24, 34, 33, 22, 20, 24, 29,
       26, 34, 33, 26, 30, 28, 34, 34, 29, 29, 31, 32, 22, 34, 35, 26, 20,
       23, 32, 35, 23, 33, 24, 26, 26, 32, 34, 30, 32, 23, 32, 35, 26, 30,
       22, 25, 31, 21, 29

# 2. Find the average age of players. 

In [7]:
x=np.array(df["Age"].mean())
print(x)

27.57


# 3. Find the oldest and youngest player age. 

In [9]:
max_age=np.array(df['Age'].max())
print(max_age)
min_age=np.array(df['Age'].min())
print(min_age)

35
20


# 4. Count the total number of players above 30 years old.

In [10]:
count=np.array((df["Age"]>30).sum())
print(count)

336


# 5. Find the median batting average. 

In [6]:
median = np.array(df["Batting Average"].median())
print(median)

40.135


# 6. Find the standard deviation of strike rates. 

In [11]:
str=np.array(df['Strike Rate'].std())
print(str)

29.122759125573694


# 7. Find the 90th percentile of batting average.

In [18]:
percentile_90 = np.percentile(df["Batting Average"],90)

print(percentile_90)

55.323


# 8. Find the number of players with strike rate above 150. 

In [19]:
p = np.array(df["Strike Rate"] > 150).sum()
p

513

# 9. Reshape the first 20 batting averages into a 4x5 matrix. 

In [31]:
reshaped_avg = np.array(df["Batting Average"][:20]).reshape(4,5)
print(reshaped_avg)

[[27.7  24.61 36.87 51.81 49.8 ]
 [22.2  38.21 40.9  45.78 46.01]
 [34.59 42.43 39.24 55.4  41.21]
 [37.64 36.18 42.9  52.16 41.54]]


# 10. Compute row-wise sum of reshaped matrix. 

In [36]:
row_sum=np.sum(reshaped_avg,axis=1)
print(row_sum)

[190.79 193.1  212.87 210.42]


# 11. Compute column-wise mean of reshaped matrix. 

In [37]:
col_sum=np.sum(reshaped_avg,axis=0)
print(col_sum)

[122.13 141.43 159.91 205.15 178.56]


# 12. Transpose the reshaped matrix. 

In [38]:
transpose=reshaped_avg.T
print(transpose)

[[27.7  22.2  34.59 37.64]
 [24.61 38.21 42.43 36.18]
 [36.87 40.9  39.24 42.9 ]
 [51.81 45.78 55.4  52.16]
 [49.8  46.01 41.21 41.54]]


# 13. Find the variance of batting average. 

In [39]:
variance=np.array(df["Batting Average"].var())
print(variance)

131.6715008167167


# 14. Stack age and matches played horizontally. 

In [40]:
a=np.array(df["Age"])
b=np.array(df["Matches Played"])
stacked=np.stack((a,b))
print(stacked)

[[ 26  23  32 ...  23  35  30]
 [456 154 210 ... 126  16 146]]


# 15. Split the batting average array into 5 equal parts. 

In [41]:
s=np.array(df["Batting Average"])
split_array=np.split(s,5)
print(split_array)

[array([27.7 , 24.61, 36.87, 51.81, 49.8 , 22.2 , 38.21, 40.9 , 45.78,
       46.01, 34.59, 42.43, 39.24, 55.4 , 41.21, 37.64, 36.18, 42.9 ,
       52.16, 41.54, 46.47, 49.51, 40.81, 37.07, 55.07, 36.7 , 38.48,
       59.61, 20.01, 27.42, 35.36, 57.3 , 22.8 , 20.38, 22.11, 23.54,
       21.5 , 39.19, 43.23, 30.87, 35.93, 23.67, 33.45, 40.9 , 49.29,
       20.13, 38.69, 31.88, 54.11, 48.62, 43.56, 31.09, 56.41, 21.8 ,
       24.38, 35.67, 24.98, 58.26, 51.92, 30.36, 43.54, 59.29, 55.37,
       44.03, 56.15, 59.57, 49.73, 22.6 , 36.06, 53.51, 29.22, 53.23,
       24.81, 21.88, 35.36, 21.47, 58.29, 53.05, 52.03, 45.19, 28.65,
       40.73, 43.89, 41.  , 30.41, 40.61, 39.65, 59.85, 55.9 , 38.54,
       44.92, 49.91, 21.39, 55.8 , 54.41, 38.3 , 35.65, 30.92, 39.07,
       21.78, 54.09, 21.42, 33.16, 57.26, 49.41, 31.26, 30.11, 20.2 ,
       47.83, 21.95, 41.3 , 58.48, 24.38, 55.78, 59.66, 22.46, 55.32,
       40.64, 56.26, 42.85, 46.48, 41.75, 54.58, 49.36, 40.85, 54.73,
       29.81, 26.29